---
- name: Copy backend dist files web server
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu

- name: Unzip backend files
  shell: |
    tar -zxvf /home/ubuntu/artifact.tar.gz
- name: Install Node
  shell: |
    cd /home/ubuntu/backend
    npm install
- name: Build Node
  shell: |
    cd /home/ubuntu/backend
    npm run build
- name: Start PM2
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start

- name: deploy
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start