---
- name: Copy backend dist files web server
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu

- name: Unzip backend files
  shell: |
    tar -xvzf /home/ubuntu/artifact.tar.gz
- name: Install Node
  shell: |
    cd /home/ubuntu
    npm install
- name: Build Node
  shell: |
    cd /home/ubuntu
    npm run build
- name: Start PM2
  shell: |
    cd /home/ubuntu
    pm2 start npm --name backend -- start
